# 317301596
# zinkevd

compile: bin
	javac -cp src -d bin src/Factorial.java src/Sort.java src/DescribeNumbers.java
run1:
	java -cp bin Factorial 20
run2:
	java -cp bin DescribeNumbers 1337 7331 -13 -37
run3:
	java -cp bin Sort asc -3242 -5555 22 -31 1333 2 44
bin:
	mkdir bin
